### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by jsmif** [Mauddib28/bleep-tool#1]
```
python3 dbus__bleep.py -m user -h
Traceback (most recent call last):
  File "/home/user/bleep-tool/dbus__bleep.py", line 155, in <module>
    import json, xmltodict
ModuleNotFoundError: No module named 'xmltodict'
```

Shouldn't your dependencies be listed somewhere in your README? (Your BSides talk you said they were listed in the github but it doesn't look like it.)

**Comment by Mauddib28** [comment]
Hello,
Yes, you are correct.  I was mistaken about having pushed the requirements.  Please allow me to generate that for you.
Also, please let me know any other issues that arise for you!

**Comment by Mauddib28** [comment]
Please try running the following command:
`python3 -m pip install xmltodict`
That should allow you to continue using BLEEP.  I'm working on adding in the instructions and a requirements.txt file to further alleviate this issue in the future.

**Comment by Mauddib28** [comment]
I made corrections to the documentation and added a requirements.txt file.  Please confirm if this alleviates the issue at your earliest convenience.

**Comment by Mauddib28** [comment]
Assuming issue resolved.  Please open a new issue for any future issues.
